# Generated by Django 4.2.2 on 2023-07-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
        migrations.RemoveField(
            model_name='filter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='price',
        ),
        migrations.AlterField(
            model_name='filter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
