# Generated by Django 4.2.2 on 2023-07-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_filter_options_remove_filter_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='title',
            new_name='product',
        ),
    ]
