# Generated by Django 4.2.2 on 2023-07-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='product',
        ),
    ]
